sudo: false
language: elixir
matrix:
  include:
  - name: "1.5.3 and 19.1"
    elixir: 1.5.3
    otp_release: 19.1
  - name: "1.8.1 and 21.2"
    elixir: 1.8.1
    otp_release: 21.2
script:
  - echo "===> Running with Erlang $TRAVIS_OTP_RELEASE";
    if [ "$TRAVIS_OTP_RELEASE" == "18.3" ]; then
      echo "===> Testing with code coverage";
      MIX_ENV=test mix coveralls.travis;
    else
      echo "===> Testing without code coverage";
      mix test;
    fi
